In [1]:
import numpy as np
import pandas as pd

import numpy as np
import torch
import torchmetrics
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

C:\Users\DU\anaconda3\Lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")


In [2]:
PATH = 'G:/Kountay Dwivedi/CHANCHAL/'
PATH2 = 'G:/Kountay Dwivedi/Chanchal Ma\'am/FRESH ANALYSIS/_FULL ANALYSIS/'
hub = pd.read_csv(PATH2+'_2020_ 20 hub genes.txt')
intersected = pd.read_csv(PATH2+'up + down intersected.txt')
# stages = pd.read_csv(PATH+'data_clinical_patient.csv')
# df = pd.read_csv(PATH+'mrna.csv')

In [3]:
intersected

genes
0      ENO1
1     AP2B1
2      IPO5
3     HMGB1
4      CCT5
..      ...
279   PDE9A
280   MTMR3
281    CBX7
282  TNRC6B
283    CNST

[284 rows x 1 columns]

In [4]:
hub_genes = hub['genes'].values

In [5]:
intersected_genes = intersected['genes'].values

In [6]:
hub_genes

array(['PRC1', 'HNRNPM', 'DTL', 'FANCI', 'EXO1', 'UBE2I', 'DICER1',
       'PTEN', 'PRPF19', 'CDC45', 'MKI67', 'EFTUD2', 'BLM', 'POLE2',
       'FANCM', 'DDX55', 'HELLS', 'HSPA4', 'PLK1', 'EGFR'], dtype=object)

In [7]:
import matplotlib.pyplot as plt
import seaborn as sea

In [8]:
df_float = pd.read_csv(PATH+'final_COAD.csv')
stages = pd.read_csv(PATH+'final_STAGES.csv')

In [9]:
labels = stages['labels']

In [10]:
df_float.drop(columns=['Unnamed: 0'], inplace=True)
df_float.reset_index(drop=True, inplace=True)

In [11]:
df_float

UBE2Q2P2  HMGB1P1  RNU12-2P   SSX9P   EZHIP  EFCAB8  SRP14P1  TRIM75P  \
0      0.8261  -1.1189    1.7499 -1.8931 -0.3378  0.5554  -0.8601  -0.2604   
1     -0.9395  -1.1424   -0.7737 -1.8931 -0.6998  0.5560  -0.8594  -2.6791   
2      0.3535  -1.1351    2.8263 -1.8931 -0.6998  0.7784  -0.4951  -2.6791   
3      1.0773  -1.0950    2.0144 -1.8931 -0.6998  0.4246  -1.9598   1.1280   
4      0.7612  -0.2275    0.8686 -1.8931  0.0695  1.3499  -0.6683  -2.6791   
..        ...      ...       ...     ...     ...     ...      ...      ...   
572   -0.8343   0.4415    0.2275 -1.8931 -0.6998 -0.8028  -1.4803  -2.6791   
573    0.4208   0.3366   -2.2343 -1.8931 -0.6998  1.9798   0.1781  -2.6791   
574    0.8838   0.0532    0.0831 -1.8931 -0.6998 -0.8440  -0.5739  -2.6791   
575   -0.1445  -0.3383   -0.9346 -1.8931 -0.6998 -0.8604  -1.3327  -2.6791   
576   -0.8858  -1.7363   -2.2343 -1.8931 -0.6998 -0.4746  -1.6910  -2.6791   

     REXO1L6P  HSPB1P1  ...  ZWILCH   ZWINT    ZXDA    ZXDB    ZXDC  ZYG11A  \
0     -5.0064   0.5280  ... -0.5482 -1.0930  0.6817  0.1882  0.5793  1.2642   
1     -5.0064   1.4720  ... -2.2342 -1.9371 -0.4061 -0.3439  0.7280 -0.6742   
2     -5.0064   0.1394  ...  0.0098  0.0907 -0.8359 -0.4555  0.5033 -1.3802   
3     -5.0064  -1.7027  ... -0.2223  1.1799  0.1898  0.5628  1.4072 -0.7399   
4     -5.0064  -0.0404  ...  0.3229  0.7104 -0.1337 -0.5512  0.4074  3.4381   
..        ...      ...  ...     ...     ...     ...     ...     ...     ...   
572   -5.0064  -1.1820  ... -0.4404  1.2369 -0.2168 -0.1447  1.3019 -1.3802   
573   -5.0064   0.4278  ... -0.4106  1.2809 -2.4102 -1.6774 -0.6188 -0.7104   
574   -5.0064   0.5474  ...  0.2872  1.2282  0.1359 -0.7508  2.6089 -1.3802   
575   -5.0064  -0.1114  ... -0.5774  1.2676  0.1032  0.3366 -1.1092 -1.3802   
576   -5.0064  -0.7632  ...  0.5594 -0.2933  0.2193 -0.4574 -0.5047  0.0360   

     ZYG11B     ZYX   ZZEF1    ZZZ3  
0   -0.1583  0.7335  0.3081  0.6221  
1   -1.8074 -0.0129  0.0726 -1.9346  
2    0.3957 -0.1193  2.0492 -0.5793  
3   -0.6821 -0.2767 -0.1681 -0.3435  
4   -0.4145  0.6958  0.3596  0.3078  
..      ...     ...     ...     ...  
572 -0.1805  0.0625  1.3433 -0.2232  
573  0.7543 -0.2133 -0.8845  0.5903  
574 -0.0665 -2.2308 -0.5859  0.1875  
575 -0.1436 -0.0041 -0.4211 -0.7028  
576  1.9091  1.4714  1.3304  0.3210  

[577 rows x 19933 columns]

In [12]:
stages[stages.AJCC_PATHOLOGIC_TUMOR_STAGE == 'STAGE V'].count()

PATIENT_ID                     0
labels                         0
AJCC_PATHOLOGIC_TUMOR_STAGE    0
dtype: int64

# with intersected and hub genes

In [13]:
df_float = df_float[df_float.columns.intersection(intersected_genes)]

In [14]:
df_float

AAK1   ACSF2  AHCTF1    AHCY  AKAP13   AP2B1  ARID4A   ATAD5  ATP11A  \
0    0.6588 -0.5508 -0.0556  0.0759  1.1709  0.7794  0.1742 -0.3855  0.0990   
1   -0.0182  1.4807 -0.1324 -0.7653 -0.3062  0.8367 -0.3992 -0.7557 -0.2461   
2   -0.2947  0.2296  0.6067 -1.0186  1.0722  0.9012 -0.2277  0.2784 -0.1274   
3    0.7478  0.3941  0.7953  0.7742 -0.4842  0.9509  0.1431  1.2029 -0.0275   
4    0.5406 -0.9950  0.2250 -0.8069  0.2392  0.0575 -0.3294  0.7685 -0.5482   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
572 -0.3442 -0.0578  0.8761 -0.8052 -0.0100 -1.2349  0.4647  0.0562  0.7583   
573  0.8733  0.7162  0.7768  0.1508 -2.2191  0.7010 -0.7991  0.6276 -0.0211   
574 -0.1774 -1.5651  0.2742  0.7555  0.0465 -0.7083 -0.2423  1.3251  2.0216   
575  2.1915  0.5950 -0.0933 -0.2221 -1.2919  1.6487 -1.3256  0.6103 -0.8982   
576  1.5853 -1.4680  0.7621 -2.6686  2.7174 -0.6065  0.7046 -0.1176  0.3525   

     ATP2A3  ...  ZNF207  ZNF264  ZNF281  ZNF337  ZNF343   ZNF44  ZNF473  \
0    0.7243  ...  0.3758  0.8302 -0.3471  1.7033  1.7003  0.8700 -0.3511   
1   -0.3333  ... -0.3558  0.6376 -1.7172  2.6965  0.8496  2.0586  0.5455   
2    0.9575  ...  0.2562 -2.0466 -0.4852  0.2198  0.4555  1.2013 -0.1161   
3   -1.2090  ...  0.1035  0.2425 -0.7498  1.6884  1.0626 -0.1774  0.6970   
4   -0.8879  ... -0.4755  0.5336  0.1312  0.2550  0.9967 -0.8663 -0.8640   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
572  0.2155  ... -1.1923  0.2578 -0.4827  0.4406 -0.5938  0.7827 -0.0808   
573 -2.1087  ... -1.0185 -0.3907 -1.1534 -0.1870 -1.1587  0.2278  0.2611   
574 -0.8057  ...  0.2925  1.0944  0.0143 -1.0734 -0.4816  0.2803 -0.0719   
575 -1.5202  ... -0.1466 -0.1142 -0.9030 -0.6082  0.3986  0.5902  0.2435   
576  0.8936  ... -1.5302  0.9856  2.7911 -0.3648 -0.0294 -0.4375 -0.2596   

     ZNF770  ZWILCH   ZZEF1  
0    0.9673 -0.5482  0.3081  
1   -1.9150 -2.2342  0.0726  
2   -0.0954  0.0098  2.0492  
3    0.1633 -0.2223 -0.1681  
4   -0.0397  0.3229  0.3596  
..      ...     ...     ...  
572 -0.4124 -0.4404  1.3433  
573 -1.5494 -0.4106 -0.8845  
574  1.0088  0.2872 -0.5859  
575 -0.5258 -0.5774 -0.4211  
576  0.4542  0.5594  1.3304  

[577 rows x 284 columns]

In [15]:
X = np.array(df_float)
y = np.array(labels)

In [16]:
num_classes = len(np.unique(y))

In [17]:
from imblearn.combine import SMOTETomek

In [18]:
sme = SMOTETomek()

In [19]:
X_sme, y_sme = sme.fit_resample(X, y)

In [20]:
y_sme_id = pd.Index(y_sme)

In [21]:
y_sme_id.value_counts()

3    220
0    218
2    217
1    215
dtype: int64

In [22]:
# import numpy as np
# import xgboost as xgb
# from sklearn.model_selection import StratifiedKFold
# from sklearn.metrics import accuracy_score
# from sklearn import svm

# # Assuming you have your dataset X (features) and y (labels)

# # Define the number of folds
# num_folds = 100

# # Initialize the StratifiedKFold cross-validator
# skf = StratifiedKFold(n_splits=num_folds, shuffle=True)

# # Initialize a list to store accuracy scores for each fold
# accuracy_scores = []
# conf_mat_sum = []

# # Iterate through each fold
# for fold, (train_index, test_index) in enumerate(skf.split(X_sme, y_sme)):
#     print(f"Fold {fold + 1}/{num_folds}")
    
#     # Split data into train and test sets for this fold
#     X_train, X_test = X_sme[train_index], X_sme[test_index]
#     y_train, y_test = y_sme[train_index], y_sme[test_index]
    
#     # Initialize the XGBoost classifier
#     clf = xgb.XGBClassifier(objective='multi:softmax', num_class=num_classes)

#     # Train the classifier on the training data
#     clf.fit(X_train, y_train)
    
#     # Make predictions on the test data
#     y_pred = clf.predict(X_test)
    
#     # Calculate accuracy for this fold
#     accuracy = accuracy_score(y_test, y_pred)
#     accuracy_scores.append(accuracy)
#     conf_mat = confusion_matrix(y_test, y_pred)
#     conf_mat_sum.append(conf_mat)
    
#     print(f"Accuracy: {accuracy:.4f}")
#     print(conf_mat)
    

# # Calculate and print the mean accuracy across all folds
# mean_accuracy = np.mean(accuracy_scores)
# print(f"Mean Accuracy: {mean_accuracy:.4f}")


In [23]:
# summ = np.sum(conf_mat_sum, axis=0)

In [24]:
# summ

In [25]:
# Define the neural network model
class SimpleClassifier(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(SimpleClassifier, self).__init__()
        self.f1 = nn.Linear(input_size, hidden_size)
        self.b1 = nn.BatchNorm1d(hidden_size)
        self.d1 = nn.Dropout(0.3)
        self.a1 = nn.ReLU(inplace=True)
        
        self.f2 = nn.Linear(hidden_size, hidden_size)
        self.b2 = nn.BatchNorm1d(hidden_size)
        self.d2 = nn.Dropout(0.2)
        self.a2 = nn.LeakyReLU(inplace=True)
        
        
        self.f3 = nn.Linear(hidden_size, hidden_size)
        self.b3 = nn.BatchNorm1d(hidden_size)
        self.d3 = nn.Dropout(0.1)
        self.a3 = nn.LeakyReLU(inplace=True)
        
        
        self.f4 = nn.Linear(hidden_size, hidden_size)
        self.b4 = nn.BatchNorm1d(hidden_size)
        self.d4 = nn.Dropout(0.1)
        self.a4 = nn.ReLU(inplace=True)
        
        
        self.final = nn.Linear(hidden_size, num_classes)
        self.sm = nn.LogSoftmax(dim=1)
    
    def forward(self, x):
        x1 = self.a1(self.d1(self.b1(self.f1(x))))
        x2 = self.a2(self.d2(self.b2(self.f2(x1)+x1)))
        x3 = self.a3(self.d3(self.b3(self.f3(x2))))
        x4 = self.a4(self.d4(self.b4(self.f4(x3)+x3)))
        
        x_final = self.final(x4)
        return self.sm(x_final)

In [26]:
!pip install torchsummary

In [27]:
from torchsummary import summary

In [28]:
model = SimpleClassifier(284, 1024, 4)


In [29]:
print(model)

SimpleClassifier(
  (f1): Linear(in_features=284, out_features=1024, bias=True)
  (b1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (d1): Dropout(p=0.3, inplace=False)
  (a1): ReLU(inplace=True)
  (f2): Linear(in_features=1024, out_features=1024, bias=True)
  (b2): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (d2): Dropout(p=0.2, inplace=False)
  (a2): LeakyReLU(negative_slope=0.01, inplace=True)
  (f3): Linear(in_features=1024, out_features=1024, bias=True)
  (b3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (d3): Dropout(p=0.1, inplace=False)
  (a3): LeakyReLU(negative_slope=0.01, inplace=True)
  (f4): Linear(in_features=1024, out_features=1024, bias=True)
  (b4): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (d4): Dropout(p=0.1, inplace=False)
  (a4): ReLU(inplace=True)
  (final): Linear(in_features=1024, out_features=4, bias=Tr

In [30]:
test_acc = []
conf_mat_sum_nn = []
for i in range(100):
    seed = i
    
    # Convert your dataset to PyTorch tensors and move to GPU if available
    X_sme_torch = torch.tensor(X_sme, dtype=torch.float32)
    y_sme_torch = torch.tensor(y_sme, dtype=torch.long)  # Assuming y contains integer class labels

    # Split the dataset into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(
        X_sme_torch,
        y_sme_torch,
        stratify=y_sme_torch,
        test_size=0.01,
        random_state=seed
    )

    # Instantiate the model and move to GPU
    input_size = X_sme_torch.shape[1]  # Number of features
    hidden_size = 1024
    num_classes = len(np.unique(y_sme))  # Number of unique class labels
    model = SimpleClassifier(input_size, hidden_size, num_classes)
    model = model.cuda()  # Move the model to GPU

    # Move the data to GPU
    X_train = X_train.cuda()
    y_train = y_train.cuda()
    X_test = X_test.cuda()
    y_test = y_test.cuda()

    # Define loss function and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=0.001)
    num_epochs = 200


    # Training loop
    for epoch in range(num_epochs):
        optimizer.zero_grad()
        outputs = model(X_train)
        loss = criterion(outputs, y_train)
        loss.backward()
        optimizer.step()


    # Evaluate the model on the test data
    model.eval()
    with torch.no_grad():
        test_outputs = model(X_test)
        _, predicted = torch.max(test_outputs, 1)
        accuracy = accuracy_score(y_test.cpu(), predicted.cpu())
        conf_mat = confusion_matrix(y_test.cpu(), predicted.cpu())
        print(f"Test Accuracy: {accuracy:.4f}")
        print(conf_mat)
        conf_mat_sum_nn.append(conf_mat)
    
    print('********************************************')
    test_acc.append(accuracy)


Test Accuracy: 0.7778
[[2 0 0 0]
 [1 1 0 0]
 [0 0 1 1]
 [0 0 0 3]]
********************************************
Test Accuracy: 0.7778
[[1 0 1 0]
 [0 1 0 1]
 [0 0 2 0]
 [0 0 0 3]]
********************************************
Test Accuracy: 0.5556
[[1 1 0 0]
 [0 0 1 1]
 [0 1 1 0]
 [0 0 0 3]]
********************************************
Test Accuracy: 0.6667
[[2 0 0 0]
 [1 1 0 0]
 [0 1 1 0]
 [0 1 0 2]]
********************************************
Test Accuracy: 0.7778
[[2 0 0 0]
 [1 1 0 0]
 [0 1 1 0]
 [0 0 0 3]]
********************************************
Test Accuracy: 0.7778
[[2 0 0 0]
 [1 0 1 0]
 [0 0 2 0]
 [0 0 0 3]]
********************************************
Test Accuracy: 0.5556
[[2 0 0 0]
 [1 0 1 0]
 [0 0 1 1]
 [0 0 1 2]]
********************************************
Test Accuracy: 0.7778
[[2 0 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 0 0 3]]
********************************************
Test Accuracy: 0.7778
[[2 0 0 0]
 [0 1 1 0]
 [0 0 2 0]
 [0 0 1 2]]
*************************************

Test Accuracy: 0.6667
[[2 0 0 0]
 [0 1 1 0]
 [1 1 0 0]
 [0 0 0 3]]
********************************************
Test Accuracy: 0.8889
[[2 0 0 0]
 [0 2 0 0]
 [0 1 1 0]
 [0 0 0 3]]
********************************************
Test Accuracy: 0.6667
[[2 0 0 0]
 [0 1 1 0]
 [0 2 0 0]
 [0 0 0 3]]
********************************************
Test Accuracy: 0.8889
[[2 0 0 0]
 [0 1 0 1]
 [0 0 2 0]
 [0 0 0 3]]
********************************************
Test Accuracy: 0.8889
[[2 0 0 0]
 [0 2 0 0]
 [0 1 1 0]
 [0 0 0 3]]
********************************************
Test Accuracy: 0.5556
[[2 0 0 0]
 [0 0 1 1]
 [0 1 1 0]
 [0 1 0 2]]
********************************************
Test Accuracy: 0.6667
[[2 0 0 0]
 [2 0 0 0]
 [1 0 1 0]
 [0 0 0 3]]
********************************************
Test Accuracy: 0.4444
[[1 0 0 1]
 [0 0 1 1]
 [0 0 1 1]
 [0 0 1 2]]
********************************************
Test Accuracy: 0.8889
[[2 0 0 0]
 [0 1 1 0]
 [0 0 2 0]
 [0 0 0 3]]
*************************************

In [31]:
np.array(test_acc).mean()

0.7455555555555555

In [32]:
np.sum(conf_mat_sum_nn, axis=0)

array([[183,   7,   5,   5],
       [ 28,  93,  51,  28],
       [ 15,  47, 118,  20],
       [  4,   7,  12, 277]], dtype=int64)